### ISSUE TITLE
Chrome and IE11/Edge rendering LTR instead of RTL

### ISSUE THREAD

**Issue by andjc** [athinkra/mende-kikakui#1]
Google Chrome on all platforms, and IE11 on all versions of Windows, and Edge on Win10 all display Mende Kikakui strings as LTR rather than RTL.

Bug has been filled for Chrome. See [Issue 614896](https://bugs.chromium.org/p/chromium/issues/detail?id=614896&q=mende%20kikakui&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

Working correctly in Firefox and OSX.

Not tested on Android or iOS

**Comment by srl295** [comment]
^ chrome bug marked fixed.

**Comment by zenodotus** [comment]
Great!

Charles

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
